//> using scala 3.3.7
//> using dep org.typelevel::cats-effect:3.7.0
//> using dep org.typelevel::cats-core:2.13.0
//> using dep co.fs2::fs2-core:3.13.0
//> using dep com.softwaremill.sttp.tapir::tapir-core:1.13.23
//> using dep com.softwaremill.sttp.tapir::tapir-json-circe:1.13.23
//> using dep com.softwaremill.sttp.tapir::tapir-http4s-server:1.13.23
//> using dep com.softwaremill.sttp.client3::core:3.11.0
//> using dep org.tpolecat::doobie-core:1.0.0-RC4
//> using dep org.tpolecat::doobie-hikari:1.0.0-RC4
//> using dep io.circe::circe-core:0.14.16
//> using dep io.circe::circe-generic:0.14.16
//> using dep is.cir::ciris:3.15.0
//> using dep dev.profunktor::redis4cats-effects:2.0.5
//> using dep org.http4s::http4s-ember-server:0.23.34
